version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: hrkt_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hrkt-admin
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
